// Golden Path Catalog seed data (PRD FR-2).
//
// The five MVP Golden Paths. Hand-authored and reviewed — NOT generated by an
// unreviewed LLM call. Every explanation field is populated so a recommendation
// built on a path can always cite reasoning (fit criteria, rejected
// alternatives, sources, risks). `templatesReferenced` uses stable slugs that
// the Template Registry (M3) will define.

import type { NewGoldenPath } from "./schema"

export const goldenPathSeed: NewGoldenPath[] = [
  {
    slug: "ai-native-nextjs-app",
    name: "AI-native Next.js App",
    summary:
      "Understand a modern web app built with Next.js, React, and heavy AI " +
      "assistance — the most common shape of a vibe-coded portfolio project.",
    targetProjectType:
      "A Next.js + React web application generated or heavily scaffolded with AI tools.",
    fitCriteria:
      "Use this path if your project has a package.json with `next` and " +
      "`react`, an `app/` (or `pages/`) directory, and you cannot fully " +
      "explain the routing, the server/client split, or why the dependencies " +
      "are there.",
    steps: [
      {
        title: "Find where the app starts",
        detail:
          "Locate the root layout and the home route (app/layout.tsx, " +
          "app/page.tsx) and sketch the route tree from the app/ directory.",
      },
      {
        title: "Understand the server/client boundary",
        detail:
          "Identify which components are React Server Components and which " +
          "carry 'use client'. Explain why each client component needs to be one.",
      },
      {
        title: "Trace how data reaches a page",
        detail:
          "Follow one page's data: server fetching, props, or server actions — " +
          "from source to rendered output.",
      },
      {
        title: "Understand the styling setup",
        detail:
          "Identify the styling system (Tailwind, CSS modules, shadcn/ui) and " +
          "how a component gets its styles.",
      },
      {
        title: "Justify the dependency list",
        detail:
          "Go through package.json and state, for each major dependency, what " +
          "it does and why this project needs it.",
      },
      {
        title: "Know how it builds and ships",
        detail:
          "Run the production build, read its output, and explain how the app " +
          "would be deployed.",
      },
    ],
    templatesReferenced: ["create-next-app", "shadcn-ui-monorepo", "t3-stack"],
    qualityGates: [
      "The production build completes without errors",
      "Type-checking passes",
      "You can name the purpose of every dependency in package.json",
    ],
    learningOutcomes: [
      "Explain the Next.js App Router and the server/client component split",
      "Describe how a request flows from URL to rendered page",
      "Justify each major dependency in the project",
    ],
    rejectedAlternatives: [
      {
        name: "Plain React + Vite single-page app",
        reason:
          "No built-in routing or server rendering — a Next.js project's " +
          "structure only makes sense once you see what the framework provides.",
      },
      {
        name: "A generic 'learn React' course",
        reason:
          "Teaches React in the abstract instead of the specific app the user " +
          "already has and needs to defend.",
      },
    ],
    sources: [
      { label: "Next.js App Router docs", url: "https://nextjs.org/docs/app" },
      {
        label: "React Server Components",
        url: "https://react.dev/reference/rsc/server-components",
      },
    ],
    risks: [
      "AI-generated Next.js apps often mark components 'use client' that do " +
        "not need it — watch for an unnecessarily large client bundle.",
      "Generated dependency lists can include packages the app never imports.",
    ],
  },
  {
    slug: "agentic-ccpm-workflow",
    name: "Agentic CCPM Workflow",
    summary:
      "Understand a project built and managed with an agentic, spec-driven " +
      "workflow — PRDs, epics, issues, and AI agents executing bounded tasks.",
    targetProjectType:
      "A repository whose development is driven by CCPM (or a similar " +
      "spec → epic → issue workflow) with AI agents doing the implementation.",
    fitCriteria:
      "Use this path if your repo has a .claude/ directory, PRDs and epics, " +
      "GitHub issues that map to tasks, and you want to understand how the " +
      "work was planned and executed — not just the code.",
    steps: [
      {
        title: "Read the PRD",
        detail:
          "Find the product requirement documents and understand what was " +
          "scoped, and explicitly what was not.",
      },
      {
        title: "Follow PRD → epic → tasks",
        detail:
          "See how a PRD became a technical epic and a set of numbered, " +
          "bounded task files.",
      },
      {
        title: "Map tasks to issues and commits",
        detail:
          "Trace how each task became a GitHub issue and then one or more " +
          "commits or pull requests.",
      },
      {
        title: "Understand the quality gates",
        detail:
          "Identify the CI checks, the review step, and the project's " +
          "definition of done.",
      },
      {
        title: "Trace one feature end to end",
        detail:
          "Pick a single feature and follow it from its spec all the way to " +
          "merged, verified code.",
      },
    ],
    templatesReferenced: [
      "ccpm",
      "github-spec-kit",
      "bmad",
      "prd-template",
      "adr-template",
    ],
    qualityGates: [
      "You can point to the PRD behind any feature",
      "You can trace an issue to the commit that closed it",
      "You can explain the project's definition of done",
    ],
    learningOutcomes: [
      "Explain how a spec-driven workflow turns an idea into shipped code",
      "Describe the role of PRDs, epics, issues, and CI in delivery",
      "Read a project's history as a sequence of bounded, reviewable changes",
    ],
    rejectedAlternatives: [
      {
        name: "Reading the code top to bottom",
        reason:
          "Misses the 'why' — the workflow records intent and decisions that " +
          "the code alone does not.",
      },
      {
        name: "Ad-hoc issue tracking with no PRD spine",
        reason:
          "Without the PRD → epic → task chain, traceability breaks and the " +
          "project's reasoning is lost.",
      },
    ],
    sources: [
      { label: "CCPM (automazeio/ccpm)", url: "https://github.com/automazeio/ccpm" },
    ],
    risks: [
      "Agentic workflows produce many small commits — do not mistake commit " +
        "volume for understanding.",
      "If issues and code drift apart, the traceability the workflow promises " +
        "is already gone.",
    ],
  },
  {
    slug: "repo-understanding-review-coach",
    name: "Repo Understanding & Review Coach",
    summary:
      "Understand any unfamiliar repository through structured code review — " +
      "the most general path, and the one this product itself dogfoods.",
    targetProjectType:
      "Any repository — especially one you (or an AI) built but can no longer " +
      "fully explain.",
    fitCriteria:
      "Use this path if you have a repo and need a systematic way to " +
      "understand it: where to start, what to read, and how to know you " +
      "actually understand it.",
    steps: [
      {
        title: "Read the README and package files",
        detail: "Establish what the project claims to be and what it depends on.",
      },
      {
        title: "Map the file tree",
        detail:
          "Survey the top-level structure and identify where the real code " +
          "lives versus config and generated files.",
      },
      {
        title: "Find the entry point and trace one path",
        detail:
          "Follow execution from the start of the app to one core output, " +
          "without detouring into every branch.",
      },
      {
        title: "Review a recent change",
        detail:
          "Read a recent diff or pull request and explain, in plain words, " +
          "what it changed and why.",
      },
      {
        title: "Identify the risky parts",
        detail:
          "Find where bugs are most likely to hide and what lacks tests.",
      },
      {
        title: "Explain it back",
        detail:
          "Produce a short spoken-style walkthrough as if explaining the repo " +
          "to an interviewer.",
      },
    ],
    templatesReferenced: ["claude-code-templates", "adr-template"],
    qualityGates: [
      "You can give a two-minute spoken walkthrough of the repo",
      "You can locate where any given feature lives",
      "You can name the top three risk areas in the code",
    ],
    learningOutcomes: [
      "Systematically understand an unfamiliar codebase",
      "Read a diff and explain what changed and why",
      "Identify risk areas and missing test coverage",
    ],
    rejectedAlternatives: [
      {
        name: "Reading every file in order",
        reason:
          "Slow, and it does not build a mental model — structure-first review " +
          "reaches understanding far faster.",
      },
      {
        name: "Relying on an AI summary of the repo",
        reason:
          "An AI summary you cannot verify is just another black box; the goal " +
          "is your own understanding.",
      },
    ],
    sources: [
      {
        label: "GitHub: about pull requests and review",
        url: "https://docs.github.com/en/pull-requests",
      },
    ],
    risks: [
      "Skipping the 'explain it back' step lets you feel you understand " +
        "without ever proving it.",
      "On large repos, resist understanding everything at once — depth on one " +
        "path beats shallow coverage of all of them.",
    ],
  },
  {
    slug: "contract-first-fullstack-app",
    name: "Contract-first Fullstack App",
    summary:
      "Understand a fullstack application built around a shared API contract, " +
      "where the contract — not the code — is the source of truth.",
    targetProjectType:
      "A fullstack app (frontend + backend) with a shared API schema or typed " +
      "contract between them.",
    fitCriteria:
      "Use this path if your project has a backend and a frontend that " +
      "communicate over an API, and there is a schema or contract file " +
      "(OpenAPI, tRPC, GraphQL SDL, or shared typed schemas).",
    steps: [
      {
        title: "Find the contract",
        detail:
          "Locate the API schema or contract file — it is the source of truth " +
          "for how the two sides agree.",
      },
      {
        title: "Read the contract as the spec",
        detail: "Understand the endpoints, the request/response types, and errors.",
      },
      {
        title: "Trace one endpoint to its server handler",
        detail: "Follow a single endpoint from the contract to its implementation.",
      },
      {
        title: "Trace the same endpoint to the client call",
        detail:
          "Follow that endpoint from the contract to where the frontend calls it.",
      },
      {
        title: "Understand code generation",
        detail:
          "Identify which types or client code are generated from the contract " +
          "versus hand-written.",
      },
      {
        title: "Check for contract drift",
        detail: "Confirm the implementation still matches what the contract promises.",
      },
    ],
    templatesReferenced: ["openapi-contract-first", "t3-stack"],
    qualityGates: [
      "You can point to the contract file",
      "You can trace one endpoint from contract to server to client",
      "The contract and the implementation are in sync",
    ],
    learningOutcomes: [
      "Explain why contract-first design decouples frontend and backend",
      "Trace an API call across the whole stack",
      "Understand schema-driven code generation",
    ],
    rejectedAlternatives: [
      {
        name: "Implementation-first APIs",
        reason:
          "Without a contract, frontend and backend drift apart and the " +
          "integration becomes implicit and hard to review.",
      },
      {
        name: "Reading the frontend and backend separately",
        reason:
          "The contract is the link between them — understanding either side " +
          "alone misses how the two agree.",
      },
    ],
    sources: [
      { label: "OpenAPI Specification", url: "https://www.openapis.org/" },
    ],
    risks: [
      "A contract that is not enforced (no codegen, no validation) drifts " +
        "silently from the code.",
      "Generated code can hide complexity — know what is generated versus " +
        "hand-written.",
    ],
  },
  {
    slug: "llm-observability-eval-app",
    name: "LLM Observability & Eval App",
    summary:
      "Understand an application that calls LLMs and is instrumented for " +
      "tracing, cost tracking, and evaluation.",
    targetProjectType:
      "An app that makes LLM/AI API calls and includes — or should include — " +
      "observability or evaluation (tracing, prompt logging, evals).",
    fitCriteria:
      "Use this path if your project calls an LLM API (Claude, OpenAI, and " +
      "the like) and you want to understand the AI call flow and how its " +
      "output quality is measured.",
    steps: [
      {
        title: "Find the LLM call sites",
        detail: "Locate every place the app sends a request to a language model.",
      },
      {
        title: "Understand prompt construction",
        detail:
          "See how prompts are assembled and what context and instructions go " +
          "into each call.",
      },
      {
        title: "Trace a request through observability",
        detail:
          "Follow one call into the tracing/logging layer and read what it records.",
      },
      {
        title: "Understand evaluation",
        detail:
          "Identify how output quality is measured — evals, scoring, or test cases.",
      },
      {
        title: "Follow cost and failure handling",
        detail:
          "See how token cost, retries, timeouts, and fallbacks are handled.",
      },
    ],
    templatesReferenced: ["langfuse-starter"],
    qualityGates: [
      "You can locate every LLM call site in the app",
      "You can explain how a single call is traced",
      "You can describe how output quality is evaluated",
    ],
    learningOutcomes: [
      "Explain the full lifecycle of an LLM call inside the app",
      "Describe why observability and evals make AI features into engineering",
      "Read a trace to debug an AI failure",
    ],
    rejectedAlternatives: [
      {
        name: "Treating the LLM as a black box",
        reason:
          "Without tracing and evals you cannot debug or improve AI behavior — " +
          "observability is what makes it engineering rather than guesswork.",
      },
      {
        name: "Manual prompt testing only",
        reason:
          "It does not scale and is not reproducible; systematic evals catch " +
          "regressions a manual check will miss.",
      },
    ],
    sources: [
      { label: "Langfuse docs", url: "https://langfuse.com/docs" },
      { label: "Anthropic API docs", url: "https://docs.anthropic.com/" },
    ],
    risks: [
      "AI-generated LLM code often skips error handling, retries, and cost " +
        "limits.",
      "Without evals, a prompt change is unverifiable — a 'fix' can silently " +
        "regress other cases.",
    ],
  },
]
