// Template Registry seed data (PRD FR-2 / FR-3).
//
// The 15 MVP templates. Hand-authored and reviewed — NOT generated by an
// unreviewed LLM call (PRD NFR "No naked LLM output"). Every explanation field
// is populated: what it generates, why used, fit data (criteria + structured
// factors), risks, alternatives, learning notes, and sources.
//
// Slugs are stable kebab-case identifiers. Every slug used in any
// `goldenPathSeed[*].templatesReferenced` array resolves to an entry here —
// the referential-integrity test (`referential-integrity.test.ts`) enforces it.

import type { NewTemplate } from "./schema"

export const templateSeed: NewTemplate[] = [
  {
    slug: "shadcn-ui-monorepo",
    name: "shadcn/ui Monorepo",
    category: "Project Scaffold",
    summary:
      "A pnpm + Turborepo monorepo wired for a Next.js app plus a shared " +
      "shadcn/ui component library and shared lint/TypeScript configs.",
    whatItGenerates:
      "A workspace with `apps/web` (a Next.js app), `packages/ui` (a shadcn/ui " +
      "component library you own the source of), and shared `eslint-config` " +
      "and `typescript-config` packages, all orchestrated by Turborepo with " +
      "pnpm workspaces. Running the shadcn CLI adds component source files " +
      "directly into `packages/ui`.",
    whyUsed:
      "It gives a multi-package project a single, consistent UI system without " +
      "publishing a private npm package: components are copied into the repo " +
      "as editable source, and Turborepo caches lint/build/typecheck across " +
      "packages. It is the standard shape for a portfolio-grade Next.js repo " +
      "that wants a real design system.",
    fitCriteria:
      "Fits a project that already has — or will grow into — more than one " +
      "app or package and wants a shared, owned component library. Overkill " +
      "for a single-page throwaway app.",
    fitFactors: [
      {
        factor: "Project size",
        detail:
          "Best when the repo has, or will have, multiple apps/packages " +
          "sharing UI; a single small app does not need a monorepo.",
      },
      {
        factor: "UI ownership",
        detail:
          "Fits teams that want to own and edit component source rather than " +
          "depend on a black-box component package.",
      },
      {
        factor: "Stack",
        detail:
          "Assumes Next.js + React + Tailwind; pairs naturally with the " +
          "create-next-app and T3 stack templates.",
      },
    ],
    risks: [
      "Monorepo tooling (pnpm workspaces, Turborepo) adds setup and mental " +
        "overhead that a single-app project does not need.",
      "shadcn components are copied in as source — they do not auto-update, " +
        "so upstream fixes must be re-applied by hand.",
      "Turborepo's remote/local cache can mask a broken build if cache keys " +
        "are misconfigured.",
    ],
    alternatives: [
      {
        name: "Single Next.js app (no monorepo)",
        reason:
          "Simpler when there is exactly one deployable app and no shared " +
          "packages — less tooling to learn and maintain.",
      },
      {
        name: "Published component library (npm package)",
        reason:
          "Better when the UI library is shared across separate repos or " +
          "with external consumers, where versioned releases matter.",
      },
    ],
    learningNotes:
      "Learn why a monorepo exists: shared code with one install, one lint " +
      "config, and cached cross-package builds. Be able to explain the role " +
      "of pnpm workspaces vs Turborepo, and why shadcn/ui copies source into " +
      "your repo instead of shipping a dependency.",
    sources: [
      {
        label: "shadcn/ui — Monorepo setup",
        url: "https://ui.shadcn.com/docs/monorepo",
      },
      { label: "Turborepo docs", url: "https://turborepo.com/docs" },
      {
        label: "pnpm workspaces",
        url: "https://pnpm.io/workspaces",
      },
    ],
  },
  {
    slug: "create-next-app",
    name: "create-next-app",
    category: "Project Scaffold",
    summary:
      "The official Next.js scaffolding CLI — generates a runnable Next.js " +
      "application with the App Router, TypeScript, and tooling preconfigured.",
    whatItGenerates:
      "A complete Next.js project: an `app/` directory with a root layout and " +
      "home page, `package.json` with `next`/`react`/`react-dom`, a " +
      "`next.config` file, TypeScript config, ESLint setup, and optionally " +
      "Tailwind CSS and an `src/` directory — all immediately runnable with " +
      "`next dev`.",
    whyUsed:
      "It removes the guesswork from starting a Next.js app: the directory " +
      "layout, build pipeline, and defaults match what the framework expects, " +
      "so the project is correct from the first commit. It is the most common " +
      "starting point for an AI-assisted web project.",
    fitCriteria:
      "Fits any new React web application that wants server rendering, file- " +
      "based routing, and a production build out of the box. Not for a pure " +
      "static site or a non-React stack.",
    fitFactors: [
      {
        factor: "Framework choice",
        detail:
          "Only fits when Next.js is the intended framework; a Vite SPA or a " +
          "different meta-framework needs a different scaffold.",
      },
      {
        factor: "Greenfield vs existing",
        detail:
          "Designed for greenfield projects — it generates a fresh tree and " +
          "is not used to retrofit an existing repo.",
      },
      {
        factor: "Rendering needs",
        detail:
          "Best when the app benefits from server-side rendering, the App " +
          "Router, and React Server Components.",
      },
    ],
    risks: [
      "Defaults change between Next.js major versions — a tutorial for an " +
        "older version can describe a different generated structure.",
      "The scaffold includes config you may not understand yet (next.config, " +
        "ESLint flat config); accepting it blindly hides how the app builds.",
      "It is a starting point, not a finished architecture — data layer, " +
        "auth, and testing are still up to you.",
    ],
    alternatives: [
      {
        name: "Vite + React",
        reason:
          "Lighter and faster for a client-only single-page app that does " +
          "not need server rendering or file-based routing.",
      },
      {
        name: "T3 stack (create-t3-app)",
        reason:
          "Better when you want a typed full-stack setup (tRPC, Prisma, " +
          "NextAuth) wired in from the start, not just the Next.js shell.",
      },
    ],
    learningNotes:
      "Understand what the scaffold gave you for free: the App Router file " +
      "conventions, the server/client component split, and the build " +
      "pipeline. Be able to justify every dependency in the generated " +
      "`package.json` rather than treating it as untouchable boilerplate.",
    sources: [
      {
        label: "Next.js — Automatic installation (create-next-app)",
        url: "https://nextjs.org/docs/app/getting-started/installation",
      },
      {
        label: "Next.js App Router docs",
        url: "https://nextjs.org/docs/app",
      },
    ],
  },
  {
    slug: "t3-stack",
    name: "T3 Stack (create-t3-app)",
    category: "Project Scaffold",
    summary:
      "A typesafe full-stack Next.js scaffold — Next.js, TypeScript, Tailwind, " +
      "tRPC, Prisma/Drizzle, and NextAuth, wired together end to end.",
    whatItGenerates:
      "A Next.js project with end-to-end type safety: tRPC routers and a typed " +
      "client, an ORM (Prisma or Drizzle) with a schema, NextAuth " +
      "authentication, Tailwind styling, and environment-variable validation — " +
      "each piece optional at scaffold time and pre-integrated when chosen.",
    whyUsed:
      "It answers the full-stack questions create-next-app leaves open — how " +
      "the frontend talks to the backend, how data is modeled, how auth " +
      "works — with a typed, opinionated set of choices, so the seams between " +
      "layers are typechecked rather than stringly-typed.",
    fitCriteria:
      "Fits a full-stack app that needs its own API and database with strong " +
      "typing from database to UI. Overkill for a static or purely " +
      "client-side app, and tRPC assumes a TypeScript client and server.",
    fitFactors: [
      {
        factor: "Full-stack scope",
        detail:
          "Fits projects that own both a frontend and a backend/API in one " +
          "codebase; a frontend-only app does not need tRPC or an ORM.",
      },
      {
        factor: "Type-safety priority",
        detail:
          "Strongest fit when end-to-end TypeScript inference (DB → API → UI) " +
          "is a goal; less relevant if the API is consumed by non-TS clients.",
      },
      {
        factor: "API style",
        detail:
          "tRPC suits a TypeScript-only client/server; a public or " +
          "multi-language API is better served by a contract-first approach.",
      },
    ],
    risks: [
      "tRPC couples client and server in one TypeScript codebase — it does " +
        "not produce a language-agnostic API contract.",
      "The stack bundles several opinionated libraries; swapping one (e.g. " +
        "the ORM or auth) later means unwinding integration code.",
      "Generated apps can look complete but still lack tests, error handling, " +
        "and production database setup.",
    ],
    alternatives: [
      {
        name: "create-next-app (plain)",
        reason:
          "Better when you want to choose the data and API layers yourself, " +
          "or do not need a backend at all.",
      },
      {
        name: "OpenAPI contract-first stack",
        reason:
          "Better when the API must be language-agnostic or consumed by " +
          "clients outside the TypeScript codebase.",
      },
    ],
    learningNotes:
      "Learn how end-to-end type safety works: a change to the database " +
      "schema or a tRPC procedure surfaces as a TypeScript error in the UI. " +
      "Be able to explain why the T3 stack chose tRPC over REST/GraphQL and " +
      "what that trade-off costs.",
    sources: [
      { label: "Create T3 App docs", url: "https://create.t3.gg/" },
      { label: "tRPC docs", url: "https://trpc.io/docs" },
    ],
  },
  {
    slug: "claude-code-templates",
    name: "claude-code-templates",
    category: "Agentic Workflow",
    summary:
      "A community CLI and catalog of ready-made Claude Code configurations — " +
      "agents, commands, MCP servers, hooks, and project setups.",
    whatItGenerates:
      "Installs Claude Code configuration into a repo: `.claude/` agents and " +
      "slash commands, settings, hooks, and MCP server wiring, plus optional " +
      "analytics/health-check tooling — selected from a browsable catalog " +
      "rather than written from scratch.",
    whyUsed:
      "It gives a project a curated, reusable starting point for AI-assisted " +
      "development instead of hand-crafting agent and command definitions. " +
      "It standardizes how Claude Code is set up so the AI workflow itself is " +
      "reviewable and shareable.",
    fitCriteria:
      "Fits a repo that uses Claude Code and wants proven agent/command " +
      "configurations quickly. Not relevant to a project that does not use " +
      "Claude Code, and the catalog is community-maintained, not official.",
    fitFactors: [
      {
        factor: "Tooling",
        detail:
          "Only relevant when the project's development workflow runs on " +
          "Claude Code.",
      },
      {
        factor: "Workflow maturity",
        detail:
          "Most useful early, to bootstrap a sensible `.claude/` setup; a " +
          "mature project may already have its own tuned configuration.",
      },
      {
        factor: "Trust posture",
        detail:
          "Community content — fits teams willing to review installed agents, " +
          "commands, and hooks before relying on them.",
      },
    ],
    risks: [
      "Community-maintained, not an Anthropic product — installed agents, " +
        "hooks, and MCP configs must be reviewed before use.",
      "Hooks and MCP servers run with your permissions; an unreviewed " +
        "configuration is a real security surface.",
      "Catalog entries vary in quality and freshness and can lag behind " +
        "Claude Code itself.",
    ],
    alternatives: [
      {
        name: "Hand-written `.claude/` configuration",
        reason:
          "Better when the project needs bespoke agents/commands and the team " +
          "wants to understand every line they run.",
      },
      {
        name: "CCPM",
        reason:
          "A focused, opinionated delivery workflow rather than a broad " +
          "catalog of configurations — choose it when you want the whole " +
          "spec-to-ship process, not à-la-carte pieces.",
      },
    ],
    learningNotes:
      "Understand what a Claude Code project configuration actually contains " +
      "— agents, commands, hooks, MCP servers — and why each piece exists. " +
      "Treat installed config as code: read it, know what it can do, and be " +
      "able to explain why the project trusts it.",
    sources: [
      {
        label: "claude-code-templates (davila7/claude-code-templates)",
        url: "https://github.com/davila7/claude-code-templates",
      },
      {
        label: "Claude Code documentation",
        url: "https://docs.claude.com/en/docs/claude-code/overview",
      },
    ],
  },
  {
    slug: "ccpm",
    name: "CCPM (Claude Code Project Management)",
    category: "Agentic Workflow",
    summary:
      "A spec-driven delivery workflow for Claude Code — PRD → epic → GitHub " +
      "issues → parallel agents → shipped, reviewed code.",
    whatItGenerates:
      "A `.claude/` workflow: commands and references that turn a product idea " +
      "into a PRD, decompose it into an epic and numbered task files, sync " +
      "tasks to GitHub Issues, and track execution. It adds the scripts and " +
      "structure (`.claude/prds/`, `.claude/epics/`) that make delivery " +
      "traceable from spec to commit.",
    whyUsed:
      "It gives AI-assisted development a disciplined spine: every feature " +
      "starts from a written spec, becomes bounded tasks, and ends in a " +
      "reviewed PR. It keeps intent and decisions recorded so an AI-built " +
      "project is explainable, not just generated.",
    fitCriteria:
      "Fits a project that wants traceability from idea to merged code and " +
      "is built with AI agents doing bounded tasks. Heavyweight for a tiny " +
      "throwaway script; assumes GitHub Issues as the task store.",
    fitFactors: [
      {
        factor: "Process discipline",
        detail:
          "Fits teams that want every change tied to a spec and an issue; a " +
          "quick prototype may not justify the ceremony.",
      },
      {
        factor: "Agentic execution",
        detail:
          "Designed for AI agents executing bounded tasks, including parallel " +
          "work across worktrees.",
      },
      {
        factor: "Platform",
        detail:
          "Assumes GitHub Issues/PRs as the system of record for tasks and " +
          "review.",
      },
    ],
    risks: [
      "The PRD → epic → task ceremony is overhead that a very small project " +
        "may not repay.",
      "If issues and code drift apart, the traceability CCPM promises is " +
        "already lost — the workflow only helps if it is followed.",
      "Agentic execution produces many small commits; commit volume is not " +
        "the same as understanding.",
    ],
    alternatives: [
      {
        name: "Ad-hoc GitHub Issues (no PRD spine)",
        reason:
          "Lighter for small projects, but loses the spec → epic → task " +
          "traceability and the recorded 'why'.",
      },
      {
        name: "GitHub Spec Kit",
        reason:
          "A spec-driven alternative with a different command set — choose it " +
          "if its `/specify` → `/plan` → `/tasks` flow fits the team better.",
      },
    ],
    learningNotes:
      "Learn to read a project as a delivery process, not just code: find the " +
      "PRD behind a feature, follow it through the epic to the task, and " +
      "trace the task to the issue and commit that closed it. Be able to " +
      "state the project's definition of done.",
    sources: [
      {
        label: "CCPM (automazeio/ccpm)",
        url: "https://github.com/automazeio/ccpm",
      },
    ],
  },
  {
    slug: "github-spec-kit",
    name: "GitHub Spec Kit",
    category: "Agentic Workflow",
    summary:
      "GitHub's open-source toolkit for spec-driven development — turn a " +
      "specification into a plan, tasks, and implementation with AI agents.",
    whatItGenerates:
      "A `specify` CLI plus slash commands that scaffold a spec-driven project: " +
      "a `/constitution` of project principles, a `/specify` specification, a " +
      "`/plan` technical plan, a `/tasks` breakdown, and `/implement` " +
      "execution — stored as version-controlled markdown the agent works from.",
    whyUsed:
      "It makes the specification, not the code, the primary artifact: the AI " +
      "agent implements against an explicit, reviewed spec and plan instead of " +
      "an ambiguous prompt. It is GitHub's answer to keeping AI-assisted work " +
      "intentional and reviewable.",
    fitCriteria:
      "Fits a team that wants spec-driven development and is comfortable with " +
      "a CLI-plus-slash-command flow across coding agents. Best when the spec " +
      "is genuinely written and reviewed, not skipped.",
    fitFactors: [
      {
        factor: "Process discipline",
        detail:
          "Fits teams committed to writing and reviewing a spec before " +
          "implementation.",
      },
      {
        factor: "Agent compatibility",
        detail:
          "Designed to work across multiple coding agents, not tied to one " +
          "vendor.",
      },
      {
        factor: "Maturity",
        detail:
          "A relatively young, fast-moving project — fits teams comfortable " +
          "tracking changes to the toolkit.",
      },
    ],
    risks: [
      "Young and fast-moving — commands and conventions can change between " +
        "releases.",
      "Spec-driven only pays off if the spec is actually written and reviewed; " +
        "a skipped spec leaves the agent guessing.",
      "Overlaps with other spec-driven workflows (e.g. CCPM); running two at " +
        "once creates competing sources of truth.",
    ],
    alternatives: [
      {
        name: "CCPM",
        reason:
          "Another spec-driven workflow, tightly oriented around PRDs, epics, " +
          "and GitHub Issues with parallel agent execution.",
      },
      {
        name: "BMAD-METHOD",
        reason:
          "An agent-role-based approach (analyst, PM, architect, dev) — choose " +
          "it when you want simulated team roles rather than a spec pipeline.",
      },
    ],
    learningNotes:
      "Understand the spec-driven idea: a constitution, a specification, and a " +
      "plan precede code, and the agent implements against them. Be able to " +
      "explain how Spec Kit's `/specify` → `/plan` → `/tasks` → `/implement` " +
      "flow keeps AI work anchored to reviewed intent.",
    sources: [
      {
        label: "GitHub Spec Kit (github/spec-kit)",
        url: "https://github.com/github/spec-kit",
      },
      {
        label: "Spec-driven development with Spec Kit (GitHub Blog)",
        url: "https://github.blog/ai-and-ml/generative-ai/spec-driven-development-with-ai-get-started-with-a-new-open-source-toolkit/",
      },
    ],
  },
  {
    slug: "bmad",
    name: "BMAD-METHOD",
    category: "Agentic Workflow",
    summary:
      "An agentic workflow framework that models a software team as AI " +
      "agent roles — analyst, PM, architect, scrum master, and developer.",
    whatItGenerates:
      "A set of role-based agent definitions and templates that drive a " +
      "two-phase flow: agentic planning (an analyst, PM, and architect produce " +
      "a detailed PRD and architecture) followed by context-engineered " +
      "development (a scrum master turns the plan into hyper-detailed story " +
      "files a dev agent implements).",
    whyUsed:
      "It tackles the two biggest weaknesses of AI-assisted delivery — vague " +
      "planning and lost context — by making distinct agent roles produce " +
      "consistent, detailed artifacts so each implementation step carries the " +
      "full context it needs.",
    fitCriteria:
      "Fits a non-trivial project where planning quality and context " +
      "continuity matter and the team is willing to operate multiple agent " +
      "roles. Heavy for a small feature; the role ceremony has a learning " +
      "curve.",
    fitFactors: [
      {
        factor: "Project complexity",
        detail:
          "Pays off most on larger projects where planning and context loss " +
          "are real problems; overkill for a one-off script.",
      },
      {
        factor: "Role-based workflow",
        detail:
          "Fits teams comfortable thinking in agent roles (analyst, PM, " +
          "architect, SM, dev) rather than a single agent.",
      },
      {
        factor: "Planning emphasis",
        detail:
          "Strongest when detailed up-front planning and architecture are " +
          "valued over fast, ad-hoc iteration.",
      },
    ],
    risks: [
      "Multiple agent roles and a two-phase flow add process weight and a " +
        "learning curve.",
      "Fast-evolving framework — versions and conventions shift, so " +
        "documentation can lag.",
      "Role artifacts are only as good as their review; unreviewed PRDs and " +
        "story files still propagate mistakes downstream.",
    ],
    alternatives: [
      {
        name: "CCPM",
        reason:
          "A leaner spec-driven workflow centered on PRDs, epics, and GitHub " +
          "Issues — less role ceremony.",
      },
      {
        name: "GitHub Spec Kit",
        reason:
          "A spec-pipeline approach (constitution → spec → plan → tasks) " +
          "rather than simulated team roles.",
      },
    ],
    learningNotes:
      "Understand why BMAD splits work into agent roles: each role produces a " +
      "specific artifact, and 'context-engineered' story files exist so the " +
      "developer agent never loses the plan. Be able to explain the planning " +
      "vs development phases and what each role contributes.",
    sources: [
      {
        label: "BMAD-METHOD (bmad-code-org/BMAD-METHOD)",
        url: "https://github.com/bmad-code-org/BMAD-METHOD",
      },
    ],
  },
  {
    slug: "github-actions-node-ci",
    name: "GitHub Actions Node.js CI",
    category: "CI",
    summary:
      "A continuous-integration workflow that installs dependencies and runs " +
      "lint, typecheck, build, and tests for a Node.js project on every push " +
      "and pull request.",
    whatItGenerates:
      "A `.github/workflows/*.yml` file: a job that checks out the repo, sets " +
      "up a pinned Node.js version (often a matrix), installs dependencies " +
      "with a cached package manager, and runs the project's verification " +
      "scripts — lint, typecheck, build, test — as required status checks.",
    whyUsed:
      "It makes quality gates automatic and unavoidable: every change is " +
      "verified the same way before it can merge, so a broken build or " +
      "failing test is caught in the PR rather than on `main`. CI is the " +
      "objective enforcement of the project's definition of done.",
    fitCriteria:
      "Fits any Node.js/TypeScript project hosted on GitHub that has scripts " +
      "to run (lint, build, test). Not applicable off GitHub, and a project " +
      "with no automated checks has nothing for CI to run.",
    fitFactors: [
      {
        factor: "Hosting",
        detail:
          "GitHub Actions runs on GitHub-hosted repos; other platforms use " +
          "their own CI (GitLab CI, CircleCI).",
      },
      {
        factor: "Verification scripts",
        detail:
          "Only valuable when the project actually has lint/typecheck/build/" +
          "test scripts for the workflow to execute.",
      },
      {
        factor: "Branch protection",
        detail:
          "Most effective when CI results are wired as required checks on " +
          "protected branches.",
      },
    ],
    risks: [
      "Slow or flaky CI gets ignored or bypassed — speed and reliability " +
        "matter as much as coverage.",
      "Unpinned action versions or Node versions make builds non-reproducible " +
        "and are a supply-chain risk.",
      "Green CI only proves the configured checks passed; it does not prove " +
        "the checks are meaningful.",
    ],
    alternatives: [
      {
        name: "GitLab CI / CircleCI / other CI services",
        reason:
          "The right choice when the repo is not hosted on GitHub or the " +
          "team standardizes on a different CI provider.",
      },
      {
        name: "Local pre-commit / pre-push hooks only",
        reason:
          "Catches issues earlier on the developer's machine, but is " +
          "skippable and not a substitute for an enforced server-side gate.",
      },
    ],
    learningNotes:
      "Learn to read a CI workflow as the project's automated quality gate: " +
      "which checks run, on which events, and why they block a merge. Be able " +
      "to explain why CI runs the same `lint`/`typecheck`/`build`/`test` " +
      "commands you run locally — and why that consistency matters.",
    sources: [
      {
        label: "GitHub Actions — Building and testing Node.js",
        url: "https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs",
      },
      {
        label: "GitHub Actions documentation",
        url: "https://docs.github.com/en/actions",
      },
    ],
  },
  {
    slug: "codeql",
    name: "CodeQL Code Scanning",
    category: "Security",
    summary:
      "GitHub's static analysis engine for code scanning — finds security " +
      "vulnerabilities and bugs by querying code as data.",
    whatItGenerates:
      "A code-scanning setup — a CodeQL workflow (or default setup) that builds " +
      "a queryable database of the codebase and runs security and quality " +
      "queries, surfacing findings as code-scanning alerts in the repo's " +
      "Security tab and as annotations on pull requests.",
    whyUsed:
      "It catches whole classes of vulnerabilities — injection, unsafe data " +
      "flow, hardcoded weaknesses — automatically and on every PR, before " +
      "they reach production. It turns security review from an occasional " +
      "manual pass into a continuous, enforceable check.",
    fitCriteria:
      "Fits a GitHub-hosted project in a CodeQL-supported language " +
      "(JavaScript/TypeScript, Python, Java, Go, and others) that wants " +
      "automated security analysis. Not for unsupported languages, and " +
      "advanced setup needs a build the analyzer can observe.",
    fitFactors: [
      {
        factor: "Language support",
        detail:
          "Only analyzes CodeQL-supported languages; a project outside that " +
          "set needs a different scanner.",
      },
      {
        factor: "Hosting & licensing",
        detail:
          "Integrated with GitHub code scanning; free for public repos, and " +
          "for private repos via GitHub Advanced Security.",
      },
      {
        factor: "Security posture",
        detail:
          "Most valuable for projects that handle untrusted input or " +
          "sensitive data and want vulnerability detection on every change.",
      },
    ],
    risks: [
      "Static analysis produces false positives and can miss issues — alerts " +
        "need triage, not blind trust.",
      "Scans add time to CI, and advanced setup requires a working build the " +
        "analyzer can trace.",
      "A clean CodeQL run is not a clean bill of health; it covers only what " +
        "its queries check.",
    ],
    alternatives: [
      {
        name: "Snyk Code / SonarQube",
        reason:
          "Third-party SAST tools — useful for languages or rule sets CodeQL " +
          "does not cover, or when not on GitHub.",
      },
      {
        name: "Semgrep",
        reason:
          "Lightweight, rule-based static analysis with fast, easily " +
          "customizable patterns — a good fit for custom org-specific rules.",
      },
    ],
    learningNotes:
      "Understand what static application security testing (SAST) is: code " +
      "analyzed as data, without running it, to find vulnerable patterns. Be " +
      "able to explain why CodeQL runs in CI, how an alert reaches a PR, and " +
      "why a finding still needs human triage.",
    sources: [
      {
        label: "GitHub — About code scanning with CodeQL",
        url: "https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql",
      },
      {
        label: "CodeQL documentation",
        url: "https://codeql.github.com/docs/",
      },
    ],
  },
  {
    slug: "gitleaks",
    name: "Gitleaks Secret Scanning",
    category: "Security",
    summary:
      "An open-source scanner that detects hardcoded secrets — API keys, " +
      "tokens, passwords — in code, commits, and git history.",
    whatItGenerates:
      "A secret-scanning setup: a Gitleaks CI job or pre-commit hook (and " +
      "optional `.gitleaks.toml` config) that scans files and git history " +
      "against secret-detection rules and fails the run, or blocks the " +
      "commit, when a likely secret is found.",
    whyUsed:
      "It stops credentials from ever entering the repo — or catches them " +
      "before they merge — closing one of the most common and damaging " +
      "security mistakes. A leaked key in git history is effectively public " +
      "and must be rotated; Gitleaks exists to prevent that.",
    fitCriteria:
      "Fits any project under version control, especially one that uses API " +
      "keys, tokens, or other credentials. Largely irrelevant only for a repo " +
      "with no secrets to leak.",
    fitFactors: [
      {
        factor: "Credential exposure",
        detail:
          "Most valuable for projects that integrate with external services " +
          "and therefore handle API keys and tokens.",
      },
      {
        factor: "Integration point",
        detail:
          "Can run as a pre-commit hook (blocks early) or a CI check (blocks " +
          "the merge) — both, ideally.",
      },
      {
        factor: "Tooling-agnostic",
        detail:
          "Works on any git repo regardless of language or hosting platform.",
      },
    ],
    risks: [
      "Detection is pattern-based — it produces false positives and can miss " +
        "unusual secret formats.",
      "It detects exposure; it does not remediate. A found secret must still " +
        "be rotated and purged from history.",
      "Scanning only future commits leaves already-committed secrets in " +
        "history undetected unless a full-history scan is run.",
    ],
    alternatives: [
      {
        name: "GitHub secret scanning / push protection",
        reason:
          "Built into GitHub with partner-token detection and push blocking " +
          "— good when the repo lives on GitHub and the plan includes it.",
      },
      {
        name: "TruffleHog",
        reason:
          "Another open-source secret scanner with credential verification — " +
          "useful when you want to confirm whether a found secret is live.",
      },
    ],
    learningNotes:
      "Learn why a committed secret is treated as compromised: git history is " +
      "permanent and often public, so deletion is not enough — the secret " +
      "must be rotated. Be able to explain where Gitleaks runs (pre-commit " +
      "vs CI) and why secrets belong in `.env`, never in tracked files.",
    sources: [
      {
        label: "Gitleaks (gitleaks/gitleaks)",
        url: "https://github.com/gitleaks/gitleaks",
      },
      {
        label: "GitHub — About secret scanning",
        url: "https://docs.github.com/en/code-security/secret-scanning/introduction/about-secret-scanning",
      },
    ],
  },
  {
    slug: "dependabot",
    name: "Dependabot",
    category: "Security",
    summary:
      "GitHub's automated dependency updater — opens pull requests to keep " +
      "dependencies current and to patch known vulnerabilities.",
    whatItGenerates:
      "A `.github/dependabot.yml` configuration plus the resulting automated " +
      "pull requests: version-update PRs that bump dependencies on a schedule " +
      "and security-update PRs that patch packages with known advisories, each " +
      "with changelog and compatibility context.",
    whyUsed:
      "It keeps a project from silently rotting on outdated, vulnerable " +
      "dependencies. Updates arrive as small, reviewable, CI-checked PRs " +
      "instead of a daunting once-a-year upgrade, so security patches land " +
      "quickly and routinely.",
    fitCriteria:
      "Fits a GitHub-hosted project with a supported package ecosystem (npm, " +
      "pip, and others) and a CI suite to validate update PRs. Less useful " +
      "without CI, since updates then merge unverified.",
    fitFactors: [
      {
        factor: "Hosting & ecosystem",
        detail:
          "Native to GitHub and a fixed set of supported package ecosystems.",
      },
      {
        factor: "CI coverage",
        detail:
          "Most effective when CI runs on each update PR so a breaking bump " +
          "is caught automatically.",
      },
      {
        factor: "Maintenance cadence",
        detail:
          "Suits projects that want continuous, incremental updates rather " +
          "than rare large upgrades.",
      },
    ],
    risks: [
      "Can generate a high volume of PRs — without grouping or a review " +
        "cadence they pile up and get ignored.",
      "An automated bump can still introduce a breaking change; CI must " +
        "validate every update PR before merge.",
      "A malicious or compromised upstream release can be proposed " +
        "automatically — update PRs are not exempt from review.",
    ],
    alternatives: [
      {
        name: "Renovate",
        reason:
          "A more configurable dependency-update bot (grouping, scheduling, " +
          "auto-merge rules) that also works outside GitHub.",
      },
      {
        name: "Manual / scheduled `npm outdated` upgrades",
        reason:
          "Full control over timing and batching, at the cost of discipline " +
          "— easy to defer until updates become a large, risky upgrade.",
      },
    ],
    learningNotes:
      "Understand why dependency hygiene is a security concern: most projects " +
      "are mostly third-party code, and known CVEs are exploited in the wild. " +
      "Be able to explain the difference between Dependabot's version-update " +
      "and security-update PRs, and why CI must gate both.",
    sources: [
      {
        label: "GitHub — About Dependabot",
        url: "https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates",
      },
      {
        label: "Dependabot configuration options",
        url: "https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file",
      },
    ],
  },
  {
    slug: "adr-template",
    name: "ADR Template (Architecture Decision Record)",
    category: "Doc/Spec Template",
    summary:
      "A short, version-controlled document template that records one " +
      "architectural decision — its context, the choice made, and its " +
      "consequences.",
    whatItGenerates:
      "A markdown file per decision (commonly under `docs/decisions/` or " +
      "`docs/adr/`), numbered and dated, with a fixed set of sections: title, " +
      "status (proposed/accepted/superseded), context, the decision, the " +
      "alternatives considered, and the consequences.",
    whyUsed:
      "It captures the reasoning behind a decision at the moment it is made, " +
      "so future readers learn not just what was chosen but why, and what was " +
      "rejected. It prevents teams from re-litigating settled questions or " +
      "silently reversing decisions they no longer understand.",
    fitCriteria:
      "Fits any project that makes architectural choices worth remembering — " +
      "tooling, storage, structure. Overkill for trivial or easily reversible " +
      "decisions; the value depends on records being written when decisions " +
      "happen.",
    fitFactors: [
      {
        factor: "Decision significance",
        detail:
          "Worth an ADR when a choice is hard to reverse or shapes the " +
          "architecture; routine choices do not need one.",
      },
      {
        factor: "Team continuity",
        detail:
          "Most valuable when future contributors (or your future self) must " +
          "understand decisions they were not present for.",
      },
      {
        factor: "Lightweight process",
        detail:
          "A good fit precisely because it is small — one short markdown " +
          "file, reviewed like code, not a heavyweight design doc.",
      },
    ],
    risks: [
      "ADRs go stale if not updated — a superseded decision left marked " +
        "'accepted' is actively misleading.",
      "Writing them after the fact loses the real context and turns them " +
        "into rationalization.",
      "Too many trivial ADRs bury the few that genuinely matter.",
    ],
    alternatives: [
      {
        name: "Design docs / RFCs",
        reason:
          "Longer, more exploratory documents — better for a big decision " +
          "that needs broad discussion before it is made.",
      },
      {
        name: "Decisions recorded only in PR descriptions / commits",
        reason:
          "Lower friction, but reasoning gets scattered and is hard to find " +
          "later — no single, browsable decision log.",
      },
    ],
    learningNotes:
      "Learn to read a project through its decision log: an ADR tells you why " +
      "the storage, the framework, or the workflow is what it is. Be able to " +
      "explain a project's key choices by pointing at the ADR that recorded " +
      "each — including the alternatives that were rejected.",
    sources: [
      {
        label: "Architectural Decision Records (adr.github.io)",
        url: "https://adr.github.io/",
      },
      {
        label: "Documenting Architecture Decisions — Michael Nygard",
        url: "https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions",
      },
    ],
  },
  {
    slug: "prd-template",
    name: "PRD Template (Product Requirements Document)",
    category: "Doc/Spec Template",
    summary:
      "A structured document template that defines what a product or feature " +
      "must do, for whom, and why — and, explicitly, what is out of scope.",
    whatItGenerates:
      "A markdown specification with a consistent set of sections: an " +
      "executive summary, a problem statement, user stories with acceptance " +
      "criteria, functional and non-functional requirements, success " +
      "criteria, constraints and assumptions, an out-of-scope list, and " +
      "dependencies.",
    whyUsed:
      "It forces a feature to be thought through and agreed upon before code " +
      "is written, giving implementation a single source of truth for intent " +
      "and acceptance. In a spec-driven AI workflow it is what the agent " +
      "decomposes into an epic and tasks — the spine of traceable delivery.",
    fitCriteria:
      "Fits any feature or product non-trivial enough that intent and scope " +
      "need to be explicit and reviewed. Overkill for a one-line fix; most " +
      "valuable as the entry point of a spec-driven workflow.",
    fitFactors: [
      {
        factor: "Scope size",
        detail:
          "Worth a PRD when a change is large enough that scope, " +
          "requirements, and acceptance need agreement up front.",
      },
      {
        factor: "Workflow",
        detail:
          "Essential in a spec-driven flow (CCPM, Spec Kit) where the PRD is " +
          "the artifact later decomposed into an epic and tasks.",
      },
      {
        factor: "Stakeholder alignment",
        detail:
          "Most valuable when more than one person — or an AI agent — must " +
          "share the same understanding of what to build.",
      },
    ],
    risks: [
      "A PRD that is written and never revisited drifts from what was " +
        "actually built.",
      "Vague or untestable acceptance criteria make the PRD impossible to " +
        "verify against.",
      "Over-specifying implementation in a PRD removes design freedom that " +
        "belongs to the epic and tasks.",
    ],
    alternatives: [
      {
        name: "User stories / tickets only",
        reason:
          "Lighter for small, well-understood work, but lacks the problem " +
          "framing, non-functional requirements, and explicit out-of-scope.",
      },
      {
        name: "A one-page brief / lean canvas",
        reason:
          "Faster for early exploration when requirements are still fluid " +
          "and a full PRD would be premature.",
      },
    ],
    learningNotes:
      "Understand the PRD as the 'why' and 'what' that precedes the 'how'. Be " +
      "able to find the PRD behind a feature, read its acceptance criteria as " +
      "the definition of done, and explain what the team deliberately chose " +
      "not to build.",
    sources: [
      {
        label: "CCPM — PRD workflow (automazeio/ccpm)",
        url: "https://github.com/automazeio/ccpm",
      },
      {
        label: "Atlassian — Product requirements documents",
        url: "https://www.atlassian.com/agile/product-management/requirements",
      },
    ],
  },
  {
    slug: "openapi-contract-first",
    name: "OpenAPI Contract-First Template",
    category: "Contract",
    summary:
      "A setup where an OpenAPI specification is authored first and is the " +
      "source of truth — server stubs, typed clients, and validation are " +
      "generated from it.",
    whatItGenerates:
      "An OpenAPI document (`openapi.yaml`/`.json`) describing endpoints, " +
      "request/response schemas, and errors, plus a generation pipeline that " +
      "produces typed server interfaces or stubs, a typed client SDK, request " +
      "validation, and often interactive API documentation — all derived from " +
      "the spec.",
    whyUsed:
      "It makes the API contract explicit and language-agnostic, so frontend " +
      "and backend (and any third-party consumer) agree on one definition " +
      "before either is implemented. Code generated from the spec cannot " +
      "silently disagree with it, which keeps the two sides in sync.",
    fitCriteria:
      "Fits a project with a REST/HTTP API that is consumed across a boundary " +
      "— a separate frontend, multiple clients, or external developers. Less " +
      "suited to a TypeScript-only client/server where tRPC's inference is " +
      "simpler, or to a non-HTTP API.",
    fitFactors: [
      {
        factor: "API consumers",
        detail:
          "Strongest fit when clients are diverse or external and need a " +
          "language-neutral contract; a single TS client may not need it.",
      },
      {
        factor: "Contract enforcement",
        detail:
          "Pays off when codegen and request validation actually enforce the " +
          "spec — without enforcement the contract drifts.",
      },
      {
        factor: "API protocol",
        detail:
          "Designed for REST/HTTP APIs; GraphQL or RPC styles use their own " +
          "schema/contract mechanisms.",
      },
    ],
    risks: [
      "An OpenAPI spec that is not enforced by codegen or validation drifts " +
        "silently from the implementation.",
      "Generated code can hide complexity — you must know what is generated " +
        "versus hand-written.",
      "Authoring and maintaining a precise spec is real upfront work that a " +
        "small project may not repay.",
    ],
    alternatives: [
      {
        name: "tRPC (T3 stack)",
        reason:
          "Simpler end-to-end type safety when both client and server are " +
          "TypeScript in one codebase and no language-neutral contract is " +
          "needed.",
      },
      {
        name: "GraphQL with an SDL schema",
        reason:
          "A different contract-first model — choose it when clients need " +
          "flexible, client-shaped queries rather than fixed REST endpoints.",
      },
    ],
    learningNotes:
      "Understand why contract-first decouples a frontend and backend: the " +
      "spec, not anyone's code, is the agreement. Be able to point to the " +
      "OpenAPI file, tell which code is generated from it, trace one endpoint " +
      "across the stack, and explain how contract drift is detected.",
    sources: [
      {
        label: "OpenAPI Specification",
        url: "https://www.openapis.org/",
      },
      {
        label: "OpenAPI Initiative — What is OpenAPI",
        url: "https://www.openapis.org/what-is-openapi",
      },
    ],
  },
  {
    slug: "langfuse-starter",
    name: "Langfuse Integration Starter",
    category: "Observability",
    summary:
      "An integration starter that instruments an LLM application with " +
      "Langfuse for tracing, prompt logging, cost tracking, and evaluation.",
    whatItGenerates:
      "The wiring to make LLM calls observable: a configured Langfuse SDK " +
      "client, traced LLM calls (often via an SDK wrapper or callback " +
      "handler), prompt and completion logging with token and cost capture, " +
      "and the hooks to record scores and run evaluations on production " +
      "traces.",
    whyUsed:
      "It turns LLM features from a black box into something you can debug " +
      "and improve: every call is traced, its cost is visible, and output " +
      "quality can be measured with evals. Without observability an AI " +
      "feature cannot be operated as engineering.",
    fitCriteria:
      "Fits any application that makes LLM/AI API calls and needs to debug, " +
      "cost-control, or evaluate them. Unnecessary for an app with no LLM " +
      "calls; for a tiny prototype the instrumentation may outweigh the " +
      "benefit.",
    fitFactors: [
      {
        factor: "LLM usage",
        detail:
          "Only relevant once the app actually calls language models; the " +
          "more calls and the more complex the chains, the higher the value.",
      },
      {
        factor: "Operational maturity",
        detail:
          "Fits projects moving an AI feature toward production, where cost, " +
          "latency, and quality must be measured.",
      },
      {
        factor: "Deployment model",
        detail:
          "Works with Langfuse Cloud or a self-hosted instance — fits teams " +
          "that can run or subscribe to one.",
      },
    ],
    risks: [
      "Tracing adds a dependency and a data sink — prompts and outputs may " +
        "contain sensitive data that is then stored.",
      "Instrumentation has some latency and cost overhead; it must be " +
        "configured, not bolted on blindly.",
      "Collecting traces is not the same as evaluating — without scoring and " +
        "evals the data is observed but not acted on.",
    ],
    alternatives: [
      {
        name: "LangSmith",
        reason:
          "A comparable LLM observability and eval platform, tightly tied to " +
          "the LangChain ecosystem.",
      },
      {
        name: "OpenTelemetry-based tracing",
        reason:
          "A generic, vendor-neutral tracing approach — fits teams that want " +
          "LLM traces inside their existing observability stack.",
      },
    ],
    learningNotes:
      "Learn the full lifecycle of an LLM call: prompt construction, the " +
      "request, the trace it produces, its token cost, and the eval that " +
      "scores its output. Be able to explain why observability and evals are " +
      "what make AI features engineering rather than guesswork.",
    sources: [
      { label: "Langfuse documentation", url: "https://langfuse.com/docs" },
      {
        label: "Langfuse — Tracing",
        url: "https://langfuse.com/docs/tracing",
      },
    ],
  },
]
